services:
  knowtree:
    build:
      context: .
      args:
        VERSION: dev
    image: nabin-qq273274877/knowtree:latest
    container_name: knowtree
    ports:
      - "6006:6006"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
